### ISSUE TITLE
Error codes on Hybrid HVAC system

### ISSUE THREAD

**Issue by wrongisthenewright** [ysard/ebusd_configuration_chaffoteaux_bridgenet#4]
Hi,
I've just tested your brute force error discovery script, I was able to dump these correlations:
`1=102;2=1P1;3=1P2;4=1P3;5=104;6=107;7=1P4;8=1P4;9=109;10=110;11=112;12=114;13=116;14=118;15=103;16=105;17=106;18=108;19=111;20=1P5;21=1P6;22=1P7;23=1P8;24=201;25=309;26=203;27=308;28=205;29=000;30=2P2;31=209;32=301;33=303;34=304;35=000;36=306;37=000;38=110;39=112;40=122;41=123;42=311;43=312;44=5P6;45=501;46=502;47=504;48=5P1;49=5P2;50=5P3;51=5P4;52=601;53=602;54=604;55=605;56=607;57=421;58=000;59=610;60=612;61=6P1;62=6P2;63=611;64=000;65=422;66=510;67=753;68=750;69=603;71=511;73=3P9;75=620;76=621;79=752;80=976;81=972;82=973;83=974;84=975;85=978;86=979;87=980;88=981;90=974;91=755;92=944;93=945;94=946;95=140;96=1P9;97=141;100=701;101=711;102=721;105=411;112=962;113=9P9;114=990;115=971;116=970;117=961;118=960;119=2P8;120=901;121=902;122=903;123=904;124=905;125=906;126=907;127=908;128=909`

 my boiler manual (Genus One 30) reports other error codes that should be available eg. :

`801 Richiesta Taratura Automatica (Auto Calibration needed)
802 Taratura automatica non riuscita (Auto calibration error)
803 Sttaggio parametro 229 errato (Wrong setting on prameter 229 - boiler nominal power)
804 Richiesto clip-in disaccoppiatore bus801 Richiesta Taratura Automatica
802 Taratura automatica non riuscita
803 Sttaggio parametro 229 errato
(potenza nominale caldaia errata)
804 Richiesto clip-in disaccoppiatore bus (Bus decoupler clip-in required)????`

is it possible that the scripts tests only the first 128 error codes but my system has more "error slots"? Can I modify the script to test also 129-256 errors or I'm I risking of writing gibberish things on the bus?

TY

**Comment by wrongisthenewright** [comment]
Closed.
I took my courage and extended the scan range to 255, I was able to gram many more codes, in multiple cases the meaning are different from yours, I think that the codes corresponding meaning are a function of the FW/HVAC plant type.

Everyone should run the brute force script and do the mapping manually

TY&BR

**Comment by ysard** [comment]
Hi, sorry for the very late response, I've seen that you've solved your question.

Yes the 128 limit was here to reduce the guessing time since most of/all the codes (on my side) were discovered in this interval.
So my script has helped you, and I'm glad it has. I'll try to modify it to make it more accessible.

---
I “laugh” at seeing the reuse of error codes with different meanings depending on the brand, the device and perhaps the firmware version. :rofl: 


It has to be said that setting a limit of 255 codes with a 1-byte encoding is perhaps not the most pertinent idea in the design of this protocol.

In any case, in the event of a malfunction, unless you meet one of the brand's engineers, this will encourage service agents to replace the PCB rather than trying to diagnose it.

This already exists in the automotive industry with diagnostic boxes, and it's not the best thing the industry has produced for device repairability :D
